version: '3.4'

services:
  db:
    image: postgres:14.2
    ports:
      - "5432:5432"
    networks:
       - backend
  rabbitmq:
    image: rabbitmq:3.9.13-management
    hostname: my-rabbit
    ports:
      - 5672:5672
      - 15672:15672
    networks:
       - backend
networks:
  backend:
     driver: bridge